/**
 * arXiv 区分コード（例: cs.CV）→ 表示用の分野名。
 * @see https://arxiv.org/category_taxonomy
 * 未登録は空文字を返す。
 */
const LABELS: Record<string, string> = {
  "cs.AI": "人工知能",
  "cs.AR": "ハードウェアアーキテクチャ",
  "cs.CC": "計算複雑性",
  "cs.CE": "計算科学・工学・金融",
  "cs.CG": "計算幾何",
  "cs.CL": "計算言語学（自然言語処理）",
  "cs.CR": "暗号・セキュリティ",
  "cs.CV": "コンピュータビジョン・パターン認識",
  "cs.CY": "コンピュータと社会",
  "cs.DB": "データベース",
  "cs.DC": "分散・並列・クラスタ計算",
  "cs.DL": "デジタルライブラリ",
  "cs.DM": "離散数学",
  "cs.DS": "データ構造とアルゴリズム",
  "cs.ET": "新興技術",
  "cs.FL": "形式言語・オートマトン",
  "cs.GL": "総説（CS）",
  "cs.GR": "グラフィックス",
  "cs.GT": "ゲーム理論・マルチエージェント",
  "cs.HC": "ヒューマン・コンピュータ相互作用",
  "cs.IR": "情報検索",
  "cs.IT": "情報理論",
  "cs.LG": "機械学習",
  "cs.LO": "論理学（CS）",
  "cs.MA": "マルチエージェントシステム",
  "cs.MM": "マルチメディア",
  "cs.MS": "数理ソフトウェア",
  "cs.NA": "数値解析（CS）",
  "cs.NE": "ニューラル・進化計算",
  "cs.NI": "ネットワーク・インターネット構成",
  "cs.OH": "その他（CS）",
  "cs.OS": "オペレーティングシステム",
  "cs.PF": "性能評価",
  "cs.PL": "プログラミング言語",
  "cs.RO": "ロボティクス",
  "cs.SC": "数式処理",
  "cs.SD": "音声",
  "cs.SE": "ソフトウェア工学",
  "cs.SI": "ソーシャル・情報ネットワーク",
  "cs.SY": "システム制御",
  "stat.AP": "応用統計",
  "stat.CO": "計算統計",
  "stat.ME": "統計手法",
  "stat.ML": "機械学習（統計）",
  "stat.OT": "その他（統計）",
  "stat.TH": "統計理論",
  "eess.AS": "音声・信号処理",
  "eess.IV": "画像・映像処理",
  "eess.SP": "信号処理",
  "eess.SY": "システム・制御（工学）",
  "math.OC": "最適化・制御（数学）",
  "math.PR": "確率論",
  "q-bio.NC": "神経科学・計算",
  "physics.soc-ph": "社会・交叉領域物理学",
};

export function arxivCategoryLabelJa(code: string): string {
  return LABELS[code.trim()] ?? "";
}
